import type { Metadata } from "next";
import "./globals.css";

import { cn } from "@/lib/utils";
import { Navbar } from "@/components/navbar";
import { SessionProvider } from "next-auth/react";
import { Analytics } from '@vercel/analytics/next';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-white text-gray-900")}>
        {/* Navbar */}
        <SessionProvider >
          <Navbar />
        </SessionProvider >
        {children}
        <Analytics />
        {/* Page Content */}
        <main className="mx-auto max-w-6xl px-6 py-10">{children}</main>
      </body>
    </html>
  );
}
